title: Michael Micah
logo: /assets/img/michael.jpg
description: Transforming raw data into actionable insights.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-Minimal
# supported themes
  # GitHub Pages supports the following themes:
                # Architect
                # Cayman
                # Dinky
                # Hacker
                # Leap day
                # Merlot
                # Midnight
                # Minima
                # Minimal <
                # Modernist
                # Slate
                # Tactile
                # Time machine
