title: Michael Micah
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
# supported themes
  # GitHub Pages supports the following themes:
                # Architect
                # Cayman
                # Dinky
                # Hacker
                # Leap day
                # Merlot
                # Midnight
                # Minima
                # Minimal
                # Modernist
                # Slate
                # Tactile
                # Time machine
